"""initial

Revision ID: 504c1619f848
Revises:
Create Date: 2026-01-15 14:44:29.146296

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "504c1619f848"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
