"""types

Revision ID: 8207457cc1f6
Revises: 504c1619f848
Create Date: 2026-01-15 17:07:32.556136

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8207457cc1f6"
down_revision: Union[str, Sequence[str], None] = "504c1619f848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
